<?php
/**
 * Auto-generated build info - DO NOT EDIT
 * Generated by deploy-plugin.bat
 */
if (!defined('ABSPATH')) exit;

define('CA_BUILD_TIME', '05-Thu-02 12:46:00');
define('CA_BUILD_HASH', '05-Tu-2124600');
