<?php
/**
 * Plugin Name: CheapAlarms Platform Bridge
 * Description: Hardened WordPress integration layer for CheapAlarms – exposes secure REST endpoints, admin dashboard loader, and GHL integration.
 * Version: 2.0.1
 * Author: CheapAlarms Engineering
 * Requires at least: 5.8
 * Requires PHP: 7.4
 * Text Domain: cheapalarms
 * License: Proprietary
 */

if (!defined('ABSPATH')) {
    exit;
}

define('CA_PLUGIN_PATH', rtrim(__DIR__, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR);
define('CA_PLUGIN_VERSION', '2.0.1');

// Load build info if available (generated by deploy script)
$buildInfoFile = CA_PLUGIN_PATH . 'build-info.php';
if (file_exists($buildInfoFile)) {
    require_once $buildInfoFile;
}
// Set defaults if build info not present (local development)
if (!defined('CA_BUILD_TIME')) {
    define('CA_BUILD_TIME', 'dev');
}
if (!defined('CA_BUILD_HASH')) {
    define('CA_BUILD_HASH', 'local');
}

require_once CA_PLUGIN_PATH . 'autoload.php';

// Add Composer autoloader if vendor/ exists (for Stripe PHP library)
$composerAutoload = CA_PLUGIN_PATH . 'vendor/autoload.php';
if (file_exists($composerAutoload)) {
    require_once $composerAutoload;
}

use CheapAlarms\Plugin\Plugin;

Plugin::instance()->boot();

register_activation_hook(__FILE__, function () {
    Plugin::instance()->activate();
});

register_deactivation_hook(__FILE__, function () {
    Plugin::instance()->deactivate();
});

// Show build info in plugin description (WordPress admin)
add_filter('plugin_row_meta', function ($links, $file) {
    if ($file === plugin_basename(__FILE__)) {
        $buildInfo = CA_BUILD_TIME !== 'dev' 
            ? '<span style="color:#0073aa;font-weight:500;">Build: ' . esc_html(CA_BUILD_TIME) . '</span>'
            : '<span style="color:#d63638;">Local Development</span>';
        $links[] = $buildInfo;
    }
    return $links;
}, 10, 2);

